// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IDE_TEST_002', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IDE_TEST_002', async function() {
    await driver.get("https://www.empikfoto.sk/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.css(".menu-items > li:nth-child(3) > .link-menu")).click()
    await driver.findElement(By.id("body > section > div > div.span-3-of-4.boxes > div:nth-child(2) > div > div:nth-child(5) > div > div.box_photo > a > img")).click()
    await driver.findElement(By.id("js-generator-add > span")).click()
    assert(await driver.findElement(By.linkText("Odstrániť")).getText() == "Odstrániť")
    await driver.findElement(By.linkText("Odstrániť")).click()
    assert(await driver.findElement(By.css(".cart-empty > div")).getText() == "Tvoj košík je prázdny.\\\\nPrejsť na domovskú stránku")
    await driver.findElement(By.linkText("Prejsť na domovskú stránku")).click()
  })
})
