// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IDE _TEST _001', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IDE _TEST _001', async function() {
    await driver.get("https://www.empikfoto.sk/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    {
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active strong"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(1) > a")).click()
    {
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(3) > a")).click()
    {
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(2) > a")).click()
    await driver.close()
  })
})
