Identifier: UVX025
Title: Change the domain 
Type: automatic/ Functional
Priority: Low
Assigned to: Me
Estimate: 10 min

Precondicions:
open web: https://www.empikfoto.sk/
web is functional
tested on pc browser
Selenium IDE installed

Steps:

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IDE _TEST _001', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IDE _TEST _001', async function() {

 // 1.step open web empikfoto.sk
    await driver.get("https://www.empikfoto.sk/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    {

// 2. step mouse over to roll up flag top bar
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active strong"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }

// 3. step select CZ flag
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(1) > a")).click()
    {
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(3) > a")).click()
    {

// 4. step select RO flag
      const element = await driver.findElement(By.css("li > .dropDownFlag > .active > a"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }

// 5. step select SK flag
    await driver.findElement(By.css("li > .dropDownFlag > div:nth-child(2) > a")).click()
    await driver.close()
  })
})

Expected Results:
Open the Slovak domain and change it to Czech. From Czech to Romanian and back to Slovak.
