// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IDE_TEST_004', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IDE_TEST_004', async function() {
    await driver.get("https://www.empikfoto.sk/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.findElement(By.css(".menu-items > li:nth-child(7) > .link-menu")).click()
    await driver.findElement(By.css(".span-1-of-4:nth-child(35) img")).click()
    await driver.findElement(By.id("body > section > div > div:nth-child(5) > div > div > p:nth-child(1) > a > img")).click()
    await driver.findElement(By.css(".icon-angle-right:nth-child(1)")).click()
    await driver.findElement(By.css(".bb-nav-prev")).click()
    await driver.findElement(By.css(".photo_book_type:nth-child(2)")).click()
    await driver.findElement(By.css(".photo_book_type:nth-child(3) > img")).click()
    await driver.findElement(By.css(".upper-first-letter")).click()
  })
})
