Identifier: UVX006
Title: Find a fairytale book and redirect to an app
Type: Functional / Automatic
Priority: Medium
Assigned to: Me
Estimate: 15 min

Proposition:
open web: https://www.empikfoto.sk/
web is functional
tested on pc browser
Selenium IDE installed 
app id functional

Steps:
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IDE_TEST_004', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IDE_TEST_004', async function() {

// 1.step open web empikfoto.sk
    await driver.get("https://www.empikfoto.sk/")
    await driver.manage().window().setRect({ width: 1382, height: 744 })

// 2.step click on "Všetky produkty" on top menu bar
    await driver.findElement(By.css(".menu-items > li:nth-child(7) > .link-menu")).click()

// 3.step from offer select "Rozprávky"
    await driver.findElement(By.css(".span-1-of-4:nth-child(35) img")).click()

// 4.step click on button "Pre chlapca"
    await driver.findElement(By.id("body > section > div > div:nth-child(5) > div > div > p:nth-child(1) > a > img")).click()
   
// 5.step click on arrow forward 
    await driver.findElement(By.css(".icon-angle-right:nth-child(1)")).click()
    
// 6.step click on arrow backward
    await driver.findElement(By.css(".bb-nav-prev")).click()
   
// 7.step click on "Ukážkové pozadia"
    await driver.findElement(By.css(".photo_book_type:nth-child(2)")).click()
   
// 8.step click on "Ukážkové cliparty"
    await driver.findElement(By.css(".photo_book_type:nth-child(3) > img")).click()
    
// 9.step click on button "Vytvoriť fotoknihu" and redirect to an app
    await driver.findElement(By.css(".upper-first-letter")).click()
  })
})


Expected Result: 

Select photo book targeted for boys. 
Check if book presentation is functional. 
Redirect to an app for detailed personalization.
